name: Docker Integration Test

on: [push, pull_request]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.1'

    - name: Pull Docker image
      run: docker pull karelomab/safe-python-env:latest

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install docker

    - name: Run Docker-based Integration Tests
      run: |
        python -m test.test_integration_dockerservice

