name: Python application test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.1'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask mysql-connector-python python-dotenv docker coverage
    - name: Run tests
      run: |
        coverage run -m unittest discover
        coverage report

