name: Python application test

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      MYSQL_HOST: "178.128.233.216"
      MYSQL_USER: "webapp"
      MYSQL_PASSWORD: "89e01536ac207279409d4de1e5253e01f4a1769e696db0d6062ca9b8f56767c8"
      MYSQL_DB: "codechamp"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.1'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask mysql-connector-python python-dotenv docker coverage beautifulsoup4
    - name: Run tests
      run: |
        coverage run -m unittest discover
        coverage report

